user:
  id
  name
  email
  bio
  tag_path
  is_deleted
  function:
    id
    sig
    blurb
    body
    sig_json
    body_json
    tag_path
    user_id
    function_dependency:
      function_id
      used_function_id
      origin_tag_id
  post:
    id
    body
    user_id
    reply_to_post_id
    posted_object:
      post_id
      object_type
      object_id
  followed_object:
    user_id
    object_type
    object_id
    last_read_at
tag:
  id
  name
  key
  blurb
  tag_path
  is_deleted
  is_public
  user_id (if any)
  tagged_object:
    id
    tag_id
    tag_count
    object_type
    object_id
    tag_of_object:
      id
      tagged_object_id
      user_id
      tagging_object:
        tag_of_object_id
        object_type
        object_id
